zh-hans:
  LanguageName: 简体中文
  weight: 1
  params:
    description:
    hb:
      blog:
        sidebar:
          profile:
            location: 中国
            description: >
              全栈工程师 • 热爱开源 • [HugoMods](https://hugomods.com/) 和 [HB Framework](https://hbstack.dev/) 的创建者和维护者。
zh-hant:
  LanguageName: 繁體中文
  weight: 2
  params:
    description:
    hb:
      blog:
        sidebar:
          profile:
            location: 中國
            description: >
              全棧工程師 • 熱愛開源 • [HugoMods](https://hugomods.com/) 和 [HB Framework](https://hbstack.dev/) 的創建者和維護者。
en:
  LanguageName: English
  weight: 3
  params:
    description:
    hb:
      blog:
        sidebar:
          profile:
            location: China
            description: >
              Full stack engineer • open-source software believer • creator and maintainer of [HugoMods](https://hugomods.com/) and [HB Framework](https://hbstack.dev/).
