[[main]]
  name = "Blog"
  identifier = "blog"
  weight = 1
  [main.params]
  [main.params.icon]
    vendor = "fas"
    name = "blog"

[[main]]
  name = "Projects"
  identifier = "projects"
  weight = 100
  [main.params.icon]
    vendor = "bs"
    name = "boxes"
[[main]]
  parent = "projects"
  name = "Hugo Modules"
  url = "https://github.com/hugomods"
  weight = 1
  [main.params]
    description = "Hugo Modules for building modular themes and static sites quickly."
  [main.params.icon]
    vendor = "simple"
    name = "hugo"
    color = "#FF4088"
[[main]]
  parent = "projects"
  name = "HB Framework"
  weight = 2
  url = "https://github.com/hbstack"
  [main.params]
    description = "Building fast, modern and modular static sites with Hugo and Bootstrap."
  [main.params.icon]
    vendor = "bs"
    name = "bootstrap"
    color = "#7511f6"
[[main]]
  parent = "projects"
  name = "HBS Theme"
  weight = 3
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  [main.params]
    description = "The blog theme built on top of Hugo and Bootstrap."
  [main.params.icon]
    vendor = "bs"
    name = "bootstrap"
    color = "#7511f6"
[[main]]
  parent = "projects"
  name = "CleverGo"
  weight = 4
  url = "https://clevergo.tech/"
  [main.params]
    description = "CleverGo Web Framework."
  [main.params.icon]
    vendor = "simple"
    name = "go"
    color = "#79d4fd"
