[[main]]
  name = "博客"
  identifier = "blog"
  weight = 1
  [main.params]
    icon = '<i class="fas fa-fw fa-blog"></i>'

[[main]]
  name = "項目"
  identifier = "projects"
  weight = 100
[[main]]
  parent = "projects"
  name = "HBS 主題"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  [main.params]
    icon = '<i class="fab fa-fw fa-bootstrap" style="color: #7511f6;"></i>'
    description = "Hugo Bootstrap 主題"
[[main]]
  parent = "projects"
  name = "CleverGo"
  url = "https://clevergo.tech/"
  [main.params]
    icon = '<i class="fas fa-fw fa-lightbulb" style="color: #79d4fd;"></i>'
    description = "CleverGo Web 框架"
[[main]]
  parent = "projects"
  name = "Yii2 管理後台"
  url = "https://admin.yii2.razonyang.com/"
  [main.params]
    description = "Yii2 管理後台系統"
