[[main]]
  name = "Blog"
  identifier = "blog"
  weight = 1
  [main.params]
    icon = '<i class="fas fa-fw fa-blog"></i>'

[[main]]
  name = "Projects"
  identifier = "projects"
  weight = 100
[[main]]
  parent = "projects"
  name = "HBS Theme"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  [main.params]
    icon = '<i class="fab fa-fw fa-bootstrap" style="color: #7511f6;"></i>'
    description = "Hugo Bootstrap Theme"
[[main]]
  parent = "projects"
  name = "CleverGo"
  url = "https://clevergo.tech/"
  [main.params]
    icon = '<i class="fas fa-fw fa-lightbulb" style="color: #79d4fd;"></i>'
    description = "CleverGo Web Framework"
[[main]]
  parent = "projects"
  name = "Yii2 Admin"
  url = "https://admin.yii2.razonyang.com/"
  [main.params]
    description = "Yii2 Admin System"
