proxy = "https://goproxy.io"

[[imports]]
path = "github.com/hbstack/theme-cards"

# Docs
[[imports]]
path = "github.com/hbstack/docs/modules/sticky-till-the-end"

# Blog
## Blog sidebar
[[imports]]
path = "github.com/hbstack/blog/modules/sidebar/profile"
[[imports]]
path = "github.com/hbstack/blog/modules/sidebar/posts"
[[imports]]
path = "github.com/hbstack/blog/modules/sidebar/taxonomies"
## Blog others
[[imports]]
path = "github.com/hbstack/blog/modules/sticky-till-the-end"

# Icons
[[imports]]
path = "github.com/hugomods/icons/vendors/font-awesome"
[[imports]]
path = "github.com/hugomods/icons/vendors/simple-icons"

# [[imports]]
# path = "github.com/hbstack/footer/modules/beian"

[[imports]]
path = "github.com/hbstack/meta/recommended"
