proxy: 'https://goproxy.io'
imports:
  - path: github.com/hbstack/theme-cards
  - path: github.com/hbstack/blog/modules/giscus
  - path: github.com/hbstack/blog/modules/sidebar/profile
  - path: github.com/hbstack/blog/modules/sidebar/profile
  - path: github.com/hbstack/blog/modules/sidebar/posts
  - path: github.com/hbstack/blog/modules/sidebar/taxonomies
  - path: github.com/hbstack/blog/modules/sticky-till-the-end
  - path: github.com/hbstack/docs/modules/giscus
  - path: github.com/hugomods/icons/vendors/font-awesome
  - path: github.com/hugomods/icons/vendors/simple-icons
  - path: github.com/hbstack/meta/recommended
