proxy = "https://goproxy.io"

[[imports]]
path = "github.com/hugomods/icons/vendors/font-awesome"

[[imports]]
path = "github.com/hugomods/icons/vendors/simple-icons"

[[imports]]
path = "github.com/hbstack/footer/modules/beian"

[[imports]]
path = "github.com/hbstack/meta/recommended"
