description: "Razon Yang 的博客，Web 技术开发博客"

hb:
  logo: images/logo.jpg
  # js_bundle_name: main # the JS bundle name.
  # css_bundle_name: main # the CSS bundle name.
  header:
    brand: Razon Yang # the brand name, leave it empty to use site's title.
    # logo_bg: '#712cf9' # logo background color, used by logo with transparent background.
    # see https://hbstack.dev/en/docs/modules/socials/.
    theme: classic
    socials:
      github: razonyang
      twitter: razonyang
      youtube: UCL-27ld7B6cKBxJY0GHSPbw
  footer:
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      _color: true # when false, remove the color of social icons.
      github: razonyang
      twitter: razonyang
      youtube: UCL-27ld7B6cKBxJY0GHSPbw
  blog:
    full_width: false # when true, the blog layout takes full width.
    sidebar:
      posts:
        recent_count: 5 # the number of recent posts.
        featured_count: 5 # the number of featured posts.
      taxonomies:
        count: true # whether to show the number of posts associated to the item.
        limit: 10 # the maximum number of the item.
    paginate: 12 # paginate.
    # post_thumbnail_placeholder: HB THEME # the text of thumbnail placeholder, default to site title.
    # post_thumbnail: false # whether to show the thumbnails.
    # post_date_format: ":date_long" # see https://gohugo.io/functions/dateformat/#datetime-formatting-layouts.
    home: # homepage settings.
      featured_posts: 5 # the number of the featured posts.
      # main_sections: # leave it empty to include all regular pages.
      #   - docs
      #   - blog
    giscus:
      repo: razonyang/blog
      repo_id: MDEwOlJlcG9zaXRvcnkxODM2MDQxMzc=
      category_id: DIC_kwDOCvGTqc4CTKfR
      mapping: og:title
  docs:
    giscus:
      repo: razonyang/blog
      repo_id: MDEwOlJlcG9zaXRvcnkxODM2MDQxMzc=
      category_id: DIC_kwDOCvGTqc4CTKfR
      mapping: og:title
  content_panel:
    repo:
      service: github # github or gitlab.
      repo: razonyang/blog
      branch: main
      # subpath: exampleSite
  # gallery:
  #   thumbnail_size: "x640"

seo:
  favicons: # see https://hugomods.com/en/docs/seo/#favicons-module
    icon: images/logo.jpg # use logo as favicon.

# PWA settings, see https://hugomods.com/en/docs/pwa/#site-parameters.
pwa:
  debug: false
  icon_path: images/logo.jpg
  # manifest:
    # background_color: '#712cf9'
    # theme_color: '#712cf9'
    # short_name: 'HB Theme'

# see https://hugomods.com/en/docs/search/#site-parameters
search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false
  # shortcut_search: ["/"]

mermaid:
  # replace it with other CDNs or self-hosted URLs.
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

hugopress:
  modules:
    hb-custom:
      hooks:
        # see layouts/partials/hugopress/modules/hb-custom/hooks/head-end.html.
        head-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/body-end.html.
        body-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/hb-blog-sidebar.html.
        hb-blog-sidebar:
          cacheable: true
          weight: 1
    # change the order of sidebar modules.
    hb-blog-sidebar-taxonomies:
      hooks:
        hb-blog-sidebar:
          weight: 3
    hb-blog-sidebar-posts:
      hooks:
        hb-blog-sidebar:
          weight: 2
