name: razonyang-blog

services:
  server:
    env_file: .env
    image: hugomods/hugo:exts-non-root
    command: server -p 12345
    volumes:
      - ./:/src
      - ~/.cache/hugo_cache:/tmp/hugo_cache
      - ~/Workspaces:/workspaces
    ports:
      - 12345:12345
