name: razonyang-blog

services:
  server:
    env_file: .env
    image: hugomods/hugo:exts
    command: server -p 12345 -D
    volumes:
      - ./:/src
      - hugo_cache:/tmp/hugo_cache
      - ~/Workspaces:/workspaces
    ports:
      - 12345:12345

volumes:
  hugo_cache:
    external: true
