name: razonyang-blog

services:
  server:
    env_file: .env
    image: hugomods/hugo:exts
    command: server -p 12345
    volumes:
      - $PWD:/src
      - $HOME/.cache/docker_compose_hugo_cache:/tmp/hugo_cache
      - $HOME/Workspaces:/workspaces
    ports:
      - 12345:12345
