[pwa]
[pwa.caches]
[pwa.caches.font]
strategy = 'network-first'
[pwa.caches.image]
strategy = 'network-first'
[pwa.caches.script]
strategy = 'network-first'
[pwa.caches.style]
strategy = 'network-first'
